# Generated by Django 6.0 on 2025-12-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhistory',
            name='line_manager',
            field=models.CharField(default='Not Assigned', max_length=50),
        ),
    ]
